//! \file analyze_LHE
//!
//! Code to read and analyze LHE files generated by Powheg/MadGraph
//! Fit for longitudinal polarization and FB asymmetry of lplm events
//! Do q-qbar and q-gluon cases


#include "compute_AFB.C"

// Global definitions 

struct particle {         //!< individual particle structure
    int id;                 //! pdg particle id
    int status;             //! decay status
    int mother[2];          //! particle mother indices
    int color[2];           //!< color info
    double p[5];            //! 4-vector + mass
    float vtime;            //! lifetime
    float spin;             //! spin (helicity) info
} ;

struct eventcm {          //!< useful info in various frames
    double coststar;        //! t-scattering angle
    double mtt;             //! invariant mass of ttbar pair
    double xF;              //! Feynman x of ttbar pair
} ;





// Main program  

Double_t get_AFB(Double_t M_Zp, int m_bin)
    //reweight PYTHIA samples to get AFB for given Zprime mass at a given
    //dilepton mass
{
    // Local variables 
    int i, j, k, iqk=0, iqb=0, itq=0, itb=0, ig1=0, ig2=0, ijt, njet=0, npflavor=0, nevent, nfit;
    int nqqb=0, ngg=0, itbq, itbb, itqk, itqb, itlp, itnu;
    int nup, idrup; 
    float xwgtup, scalup, aqedup, aqcdup;
    double alpha;
    static char infile[80], header[80], inp1[80], outfile0[80], outfile1[80], outfile2[80];
    FILE *ifp;
    particle in;

    long deltas, deltaus;
    double deltat;

    // Construct file name to analyze

    strcpy(infile, "Zprime_m200.lhe");
    Float_t m_bins[] = {150,200,   250,    350,    500,    700, 100000};
    const double m_low = m_bins[m_bin];
    const double m_high =m_bins[m_bin + 1];
    sprintf(infile, "lhe_files/Pythia_M3000/Zprime_m%.0f.lhe", m_low);
    //printf("Opening file %s \n", infile);
    //printf("M bins from %.0f to %.0f \n", m_low, m_high);

    Double_t M_Zp_nom = 3000.; //mass of Z_p samples were generated at


        // Make sure file is available 

        ifp = fopen(infile, "r");
    if (ifp==NULL) {
        printf("can't find %s\n",infile);
        return 1;
    }

    //  Book Histograms

    gStyle->SetOptFit(101);
    gStyle->SetHistLineWidth(2);
    static vector<TH1F*> hp(12);

    double root2 = sqrt(2.);
    double Ebeam = 6500.;
    double Pbeam = sqrt(Ebeam*Ebeam - 0.938*0.938);

    nevent=0; nfit=0;
    int nTotal =0;
    int nFail =0;
    Double_t nF = 0, nB = 0;

    // Scan throught file first for the beginning of an event record	

    while (fscanf(ifp,"%s", inp1) !=EOF) {
        if(strcmp(inp1,"<event>") == 0) {


            // event found


            // read event info

            fscanf(ifp,"%d %d %f %f %f %f", &nup, &idrup, &xwgtup, &scalup, &aqedup, &aqcdup);

            // Make a vector to hold all particles for each event

            std::vector<particle> up;

            iqk = -1; iqb = -1; itq = -1; itb = -1; ig1 = -1; ig2 = -1; ijt = -1;
            njet = 0; npflavor = 0; nqqb = 0; ngg = 0;
            int qtype = 0; // type of quark, uct = 0 , dsb = 1

            // Now loop over all particles

            for(i=0; i<nup; ++i) {
                fscanf(ifp,"%d %d %d %d %d %d %lf %lf %lf %lf %lf %f %f", &in.id, &in.status, &in.mother[0], &in.mother[1],
                        &in.color[0], &in.color[1], &in.p[0], &in.p[1], &in.p[2], &in.p[3], &in.p[4], &in.vtime, &in.spin);	
                up.push_back(in);
            } 

            //  Do event by event analysis here	

            // first, flag the stable final particles	   
            for(i=0; i<nup; ++i) {
                if(up[i].mother[0] == 0 && up[i].mother[1] == 0) {
                    if(up[i].id == 1 || (up[i].id == 2 || (up[i].id == 3 || (up[i].id == 4 || up[i].id == 5)))) {iqk = i; npflavor += up[i].id; continue;}
                    if(up[i].id == -1 || (up[i].id == -2 || (up[i].id == -3|| (up[i].id == -4 || up[i].id == -5)))) {iqb = i; npflavor += up[i].id; continue;}
                    if(ig1 == -1) {ig1 = i;} else {ig2 = i;}
                    continue;
                }
                if(up[i].mother[0] == 3 && (up[i].mother[1] == 0 || up[i].mother[1] == 3)) {
                    //printf("Hi \n");
                    //itq = mu- itb = mu + 
                    if(up[i].id == 13) {itq = i; continue;}
                    if(up[i].id == -13) {itb = i; continue;}
                    ijt = i;
                    continue;
                }

            }



            if(iqk == -1 && iqb == -1){
                printf("no quarks \n");
                nFail++;
                continue;
            }
            //          if(npflavor != 0) continue;
            if(itq == -1 || itb == -1){
                printf("no mus \n");
                nFail++;
                continue;
            }

            if(abs(up[iqk].id) % 2 == 0) qtype = 0; //u-type quark
            else qtype = 1;
            //          if(njet < 1) continue;
            //          if(njet > 0) continue;
            //          if(njet < 1) continue;

            // Next build 4-vectors for all 6 particles

            TLorentzVector tq(up[itq].p[0], up[itq].p[1], up[itq].p[2], up[itq].p[3]);
            TLorentzVector tb(up[itb].p[0], up[itb].p[1], up[itb].p[2], up[itb].p[3]);
            TLorentzVector p1(0., 0., Pbeam, Ebeam);
            TLorentzVector p2(0., 0., -Pbeam, Ebeam);
            if(iqk > -1) {
                if(up[iqk].p[2] < 0.) {
                    TLorentzVector p = p1;
                    p1 = p2;
                    p2 = p;
                }
            } else {
                if(up[iqb].p[2] > 0.) {
                    TLorentzVector p = p1;
                    p1 = p2;
                    p2 = p;
                }
            }

            // Create vectors for the parents
            TLorentzVector cm = tq + tb;
            Double_t pt = cm.Pt();
            nTotal++;

            if(cm.M() >= m_low && cm.M() <= m_high){
                ++nevent;
                // Invariant mass of pair
                double mass = cm.M();

                double xF = 2.*cm.Pz()/1300.;

                // Boost everything into the t-tbar rest frame

                TVector3 beta = -cm.BoostVector();
                tq.Boost(beta);
                tb.Boost(beta);
                p1.Boost(beta);
                p2.Boost(beta);

                // Now calculate the direction of the new z azis

                TVector3 p1u = p1.Vect();
                p1u.SetMag(1.0);
                TVector3 p2u = p2.Vect();
                p2u.SetMag(1.0);
                TVector3 pzu = p1u - p2u;
                pzu.SetMag(1.0);
                tq.RotateUz(pzu);
                double costcs = tq.CosTheta();

                Double_t weight_nom = Zp_xsec(cm.M(), costcs, M_Zp_nom, qtype);
                Double_t weight_new = Zp_xsec(cm.M(), costcs, M_Zp, qtype);

                Double_t reweight = weight_new/weight_nom;
                //printf("reweight %.3f \n", reweight);


                if(costcs > 0.){ 
                    nF+= reweight;} 
                else {
                    nB += reweight;}



            }
        }
    }

    /* close input file */

    fclose(ifp);

    Double_t AFB = ((nF - nB))/((nF+nB));
    Double_t dAFB = (1.-AFB*AFB)/sqrt((nF+nB));

    bool print = false;
    if(print){
        printf( "A_FB count = %.3f +- %.3f\n" 
                "%i events failed to id \n",
                AFB, dAFB, nFail);
        printf("Selected  %d out of %i events\n", nevent, nTotal);
    }


    return AFB;
} 

